gperf/gperf-3.1.tar.gz:
  size: 1215925
  object_id: b42dbbee-77cb-4fae-7be6-c6ba46e46ff0
  sha: sha256:588546b945bba4b70b6a3a616e80b4ab466e3f33024a352fc2198112cdbb3ae2
libseccomp/libseccomp-2.5.1.tar.gz:
  size: 638811
  object_id: 7778c273-fa7a-45b1-76b6-c2c1f907ce9e
  sha: sha256:ee307e383c77aa7995abc5ada544d51c9723ae399768a97667d4cdb3c3a30d55
pkg-config/pkg-config-0.29.2.tar.gz:
  size: 2016830
  object_id: 68ebd5e6-b02b-49fb-4fd2-a594125b3808
  sha: 76e501663b29cb7580245720edfb6106164fad2b
runc/runc-1.1.1.tar.xz:
  size: 1412548
  object_id: 3ec91d7d-b887-402e-682c-b51c17cec62c
  sha: sha256:75c1f0bb19b209412c52599e24b33ac306cf7caf772c97577b7ebe964837a54b
tini/tini-0.18.0.tar.gz:
  size: 32152
  object_id: 71944e0b-7d0e-411a-5600-1ea5eeb9f433
  sha: 27b7529ae87ea688e21d0a061b6d9299ff9362f6
