golang/golang-linux-amd64.tar.gz:
  size: 121150330
  object_id: cd3d172a-9771-4c52-69b2-31a46fd5f8a3
  sha: 3847e07c01da7cf8f4cd8b8bbfcdcf2754fe2fbf
libseccomp/libseccomp-2.4.2.tar.gz:
  size: 601014
  object_id: 5a4a65b5-0065-412e-67bf-66114cf4d423
  sha: sha256:b54f27b53884caacc932e75e6b44304ac83586e2abe7a83eca6daecc5440585b
libseccomp/libseccomp-2.4.3.tar.gz:
  size: 598147
  object_id: 6c45d1a3-6b86-40b7-6f49-c131608921ed
  sha: sha256:cf15d1421997fac45b936515af61d209c4fd788af11005d212b3d0fd71e7991d
pkg-config/pkg-config-0.29.2.tar.gz:
  size: 2016830
  object_id: 68ebd5e6-b02b-49fb-4fd2-a594125b3808
  sha: 76e501663b29cb7580245720edfb6106164fad2b
runc/runc-1.0.0-rc10.tar.gz:
  size: 1927069
  object_id: 4fb46e34-33d6-476e-5bc8-c8af73827ae7
  sha: sha256:6b44985023347fb9c5a2cc6f761df8c41cc2c84a7a68a6e6acf834dff6653a9a
runc/runc-1.0.0-rc92.tar.gz:
  size: 2061469
  object_id: 35b0f6e7-1a0d-40e1-410a-db3810dd0d83
  sha: sha256:28378df983a3c586ed3ec8c76a774a9b10f36a0c323590a284b801cce95cc61f
tini/tini-0.18.0.tar.gz:
  size: 32152
  object_id: 71944e0b-7d0e-411a-5600-1ea5eeb9f433
  sha: 27b7529ae87ea688e21d0a061b6d9299ff9362f6
